import {ScrollMotion} from '@/components/scroll-motion';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Header,Footer,ProjectVideo} from '@/components/portfolio';
import {PortfolioProvider} from '@/components/portfolio-context';
import {readContent} from '@/lib/cms-server';
import {publicContent} from '@/lib/cms-model';
import {VideoPlayer} from '@/components/video-player';
import {cache} from 'react';
export const dynamic='force-dynamic';
const load=cache(async()=>publicContent((await readContent()).content));
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){try{const {slug}=await params;const p=(await load()).projects.find(p=>p.slug===slug);return {title:p?`${p.name} — AMDV-016`:'Projeto não encontrado',description:p?.description};}catch{return {title:'AMDV-016'}}}
export default async function Project({params}:{params:Promise<{slug:string}>}){const {slug}=await params;let content;try{content=await load();}catch{return <main className="unavailable"><h1>Voltamos em instantes.</h1><a href={'/projetos/'+slug}>Tentar novamente</a></main>;}const p=content.projects.find(p=>p.slug===slug);if(!p)notFound();const gallery=p.gallery.length?p.gallery:[{url:p.image,alt:p.alt}];return <PortfolioProvider content={content}><Header/><main id="top" className="project-page section"><Link className="mono orange" href="/#trabalhos">VOLTAR AOS TRABALHOS</Link>{p.demo&&<p className="mono project-kicker">ESTUDO VISUAL / IMAGENS DEMONSTRATIVAS</p>}<h1>{p.name}<span className="orange">.</span></h1><div className="project-meta mono"><div>CLIENTE<span>{p.client}</span></div><div>ANO<span>{p.year}</span></div><div>CATEGORIA<span>{p.category}</span></div></div><p className="project-description preline">{p.description}</p><ProjectVideo video={p.video} poster={p.image} demo={p.demo}/>{p.videos.length>0&&<section className="project-video-gallery"><div className="section-meta mono"><span>VÍDEOS DO PROJETO</span><span>{String(p.videos.length).padStart(2,'0')} FILMES</span></div><div className="project-video-grid">{p.videos.map((video,i)=><VideoPlayer key={i} src={video} poster={p.image} title={`${p.name} — vídeo ${i+1}`}/>)}</div></section>}<div className="section-meta mono"><span>GALERIA</span><span>{String(gallery.length).padStart(2,'0')} FRAMES</span></div><div className="project-gallery">{gallery.map((item,i)=><img key={i} loading="lazy" src={item.url} alt={item.alt}/>)}</div><div className="project-details"><h2>POR TRÁS<br/>DO FRAME.</h2><div><p className="preline">{p.details}</p><p className="mono preline">{p.credits}{p.demo&&<><br/>ESTUDO DEMONSTRATIVO — SEM CRÉDITO DE AUTORIA</>}</p></div></div>{content.projects.length>1&&<><h2 className="other-heading">OUTRAS HISTÓRIAS<span className="orange">.</span></h2><div className="other-projects">{content.projects.filter(x=>x.slug!==slug).slice(0,2).map(x=><Link href={'/projetos/'+x.slug} key={x.slug}><img loading="lazy" src={x.image} alt={x.alt}/><h3>{x.name}</h3><p className="mono">{x.category} / {x.year}</p></Link>)}</div></>}</main><Footer/><ScrollMotion/></PortfolioProvider>}
